-- Agregar más especialidades médicas
INSERT IGNORE INTO especialidades (nombre, descripcion) VALUES
('Medicina General', 'Atención general y diagnóstico inicial'),
('Cardiología', 'Enfermedades del corazón y sistema circulatorio'),
('Neurología', 'Enfermedades del sistema nervioso'),
('Dermatología', 'Enfermedades de la piel'),
('Oftalmología', 'Enfermedades de los ojos'),
('Otorrinolaringología', 'Enfermedades de oído, nariz y garganta'),
('Ginecología', 'Salud reproductiva femenina'),
('Pediatría', 'Medicina para niños'),
('Traumatología', 'Lesiones y traumatismos'),
('Neumología', 'Enfermedades de los pulmones'),
('Gastroenterología', 'Enfermedades del sistema digestivo'),
('Reumatología', 'Enfermedades reumáticas y articulares'),
('Endocrinología', 'Enfermedades endocrinas y metabólicas'),
('Oncología', 'Tratamiento del cáncer'),
('Psiquiatría', 'Salud mental y trastornos psiquiátricos'),
('Medicina Interna', 'Enfermedades sistémicas'),
('Urología', 'Enfermedades del sistema urinario'),
('Infectología', 'Enfermedades infecciosas'),
('Radiología', 'Diagnóstico por imagen'),
('Cirugía General', 'Cirugía general y procedimientos quirúrgicos'),
('Anestesiología', 'Anestesia y cuidados perioperatorios'),
('Nefrología', 'Enfermedades de los riñones'),
('Hematología', 'Enfermedades de la sangre'),
('Ortopedia', 'Enfermedades de huesos y articulaciones'),
('Fisioterapia', 'Rehabilitación física'),
('Proctología', 'Enfermedades del recto y colon'),
('Oftalmología Pediátrica', 'Enfermedades oculares en niños'),
('Cirugía Plástica', 'Cirugía estética y reconstructiva'),
('Medicina Deportiva', 'Lesiones deportivas'),
('Alergología', 'Alergias e inmunología'),
('Nutrición', 'Nutrición y dietética'),
('Podología', 'Enfermedades de los pies'),
('Audiología', 'Sordera y problemas auditivos'),
('Estomatología', 'Enfermedades bucales'),
('Vacunología', 'Vacunación e inmunización'),
('Toxicología', 'Envenenamientos y tóxicos'),
('Neumología Pediátrica', 'Enfermedades pulmonares en niños'),
('Cardiología Pediátrica', 'Cardiopatías congénitas'),
('Gastroenterología Pediátrica', 'Enfermedades digestivas en niños'),
('Oftalmología Quirúrgica', 'Cirugía oftalmológica');
