USE clinica_espe_v2;

-- MEDICINA GENERAL - Aumentar a 150 sintomas
INSERT INTO sintomas_especialidad (palabra_clave, especialidad_id) VALUES
('fatiga extrema', 1), ('debilidad general', 1), ('malestar general', 1),
('no me siento bien', 1), ('molestia corporal', 1), ('cuerpo adolorido', 1),
('dolor generalizado', 1), ('me duele todo', 1), ('inflamacion generalizada', 1),
('enrojecimiento de cara', 1), ('cara hinchada', 1), ('ojos inflamados', 1),
('inflamacion de parpados', 1), ('bolsas bajo los ojos', 1), ('cambios en labios', 1),
('labios hinchados', 1), ('labios secos', 1), ('labios agrietados', 1),
('grietas en labios', 1), ('sequedad de boca', 1), ('labios palidos', 1),
('labios azulados', 1), ('cambios de color en piel', 1), ('piel palida', 1),
('piel grisacea', 1), ('piel con brillo', 1), ('piel opaca', 1),
('piel con escamas', 1), ('descamacion de piel', 1), ('piel con textura rara', 1),
('cambios en uñas', 1), ('uñas fragiles', 1), ('uñas deformadas', 1),
('uñas con lineas', 1), ('uñas amarillas', 1), ('uñas pálidas', 1),
('uñas azuladas', 1), ('uñas desprendidas', 1), ('cambios en cabello', 1),
('cabello debil', 1), ('cabello frágil', 1), ('cabello quebradizo', 1),
('opacidad del cabello', 1), ('cabello sin brillo', 1), ('cabello con cambios', 1),
('cambios en la voz', 1), ('voz rasposa', 1), ('voz debil', 1),
('dificultad para hablar', 1), ('afonia parcial', 1), ('cambios en gusto', 1),
('gusto metalico', 1), ('perdida de gusto', 1), ('gusto amargo', 1),
('alteracion del olfato', 1), ('perdida de olfato', 1), ('olores desagradables', 1),
('hipersensibilidad a olores', 1), ('cambios en sueno', 1), ('insomnio', 1),
('sueno excesivo', 1), ('somnolencia diurna', 1), ('pesadillas', 1),
('sueno no reparador', 1), ('dormir poco', 1), ('dormir mucho', 1),
('despertarse frecuentemente', 1), ('dificultad para dormir', 1), ('cambios de humor', 1),
('irritabilidad', 1), ('cambios emocionales', 1), ('labilidad emocional', 1),
('frialdad emocional', 1), ('falta de emociones', 1), ('apatia', 1),
('desinteres', 1), ('falta de motivacion', 1), ('tristeza', 1),
('melancolía constante', 1), ('felicidad excesiva', 1), ('euforia', 1),
('ansiedad constante', 1), ('nerviosismo', 1), ('inquietud', 1),
('agitacion', 1), ('dificultad para concentrarse', 1), ('problemas de memoria', 1),
('olvidos frecuentes', 1), ('confusion mental', 1), ('desorientacion', 1),
('perdida de conocimiento breve', 1), ('desvanecimientos', 1), ('lipotimias', 1);

-- PEDIATRÍA - Aumentar a 65 sintomas
INSERT INTO sintomas_especialidad (palabra_clave, especialidad_id) VALUES
('bebe pequeno', 2), ('bebe mucho', 2), ('bebe agitado', 2),
('bebe somnoliento', 2), ('bebe letargico', 2), ('bebe sin energia', 2),
('bebe muy palido', 2), ('bebe azulado', 2), ('bebe con frio', 2),
('bebe con calor', 2), ('bebe suda mucho', 2), ('bebe suda poco', 2),
('bebe con convulsiones', 2), ('bebe con espasmos', 2), ('bebe rigido', 2),
('bebe flacido', 2), ('bebe con reflejos anomalos', 2), ('bebe con fontanela abultada', 2),
('bebe con fontanela hundida', 2), ('bebe con cabeza grande', 2), ('bebe con cabeza pequena', 2),
('bebe con ojos saltones', 2), ('bebe con mirada fija', 2), ('bebe no parpadea', 2),
('bebe con estrabismo', 2), ('bebe con pupilas dilatadas', 2), ('bebe con pupilas contraidas', 2),
('bebe sin reaccion a ruidos', 2), ('bebe sobresaltado por ruidos', 2), ('bebe con nistagmo', 2),
('bebe con posicion anormal', 2), ('bebe sin tono muscular', 2), ('bebe con musculatura tensa', 2),
('bebe que no succiona', 2), ('bebe que succiona debilmente', 2), ('bebe con paladar hendido', 2),
('bebe con labio leporino', 2), ('bebe sin reflejo de succion', 2), ('bebe que regurgita', 2),
('bebe que vomita muchas veces', 2), ('bebe con deposiciones negras', 2), ('bebe con deposiciones rojas', 2),
('bebe con deposiciones verdes', 2), ('bebe con deposiciones liquidas', 2), ('bebe sin deposiciones', 2),
('bebe con distension abdominal', 2), ('bebe con abdomen duro', 2), ('bebe con abdomen retractil', 2),
('bebe con cicatriz', 2), ('bebe con hematomas', 2), ('bebe con moretones', 2),
('bebe con hemorragias cutaneas', 2), ('bebe con petequias', 2), ('bebe con erupciones', 2),
('bebe con ampollas', 2), ('bebe con ulceras', 2), ('bebe con gangrena', 2);

-- CARDIOLOGÍA - Aumentar a 65 sintomas
INSERT INTO sintomas_especialidad (palabra_clave, especialidad_id) VALUES
('dolor retrosesternal', 3), ('dolor substernal', 3), ('dolor precordial', 3),
('presion en pecho', 3), ('peso en pecho', 3), ('sensacion de aplastamiento', 3),
('sensacion de constriccion', 3), ('irradiacion a brazo', 3), ('irradiacion a cuello', 3),
('irradiacion a espalda', 3), ('irradiacion a mandibula', 3), ('irradiacion a abdomen', 3),
('dolor migratorio', 3), ('dolor variable', 3), ('dolor persistente', 3),
('dolor con movimiento', 3), ('dolor con respiracion', 3), ('dolor con esfuerzo', 3),
('dolor con emocion', 3), ('dolor al acostarse', 3), ('dolor al levantarse', 3),
('dolor con el frio', 3), ('dolor con el calor', 3), ('dolor con comidas', 3),
('taquicardia persistente', 3), ('bradicardia persistente', 3), ('arritmias', 3),
('latidos irregulares frecuentes', 3), ('sensacion de aleteo', 3), ('sensacion de vuelcos', 3),
('sensacion de carreras', 3), ('golpes en el pecho', 3), ('pulsaciones visibles', 3),
('pulsaciones palpables', 3), ('edema de miembros inferiores', 3), ('hinchazón de tobillos', 3),
('hinchazón de pies', 3), ('edema nocturno', 3), ('edema progresivo', 3),
('dedos en palillo de tambor', 3), ('uñas en vidrio de reloj', 3), ('cianosis periferica', 3),
('cianosis central', 3), ('palidez marcada', 3), ('coloracion azulada', 3),
('rubor facial', 3), ('frialdad de extremidades', 3), ('extremidades mojadas', 3),
('extremidades sudorosas', 3), ('pulsos debiles', 3), ('pulsos aumentados', 3),
('pulsos irregulares', 3), ('asimetria de pulsos', 3), ('ausencia de pulsos', 3),
('presion sistolica baja', 3), ('presion diastolica alta', 3), ('presion del pulso estrecha', 3),
('hipotension ortostatica', 3), ('hipertension labil', 3), ('crisis hipertensivas', 3);

-- NEUROLOGÍA - Aumentar a 65 sintomas
INSERT INTO sintomas_especialidad (palabra_clave, especialidad_id) VALUES
('debilidad focal', 6), ('debilidad progresiva', 6), ('debilidad fluctuante', 6),
('paralisis facial', 6), ('paralisis de nervios craneales', 6), ('paralisis ocular', 6),
('paralisis de mirada', 6), ('ptosis palpebral', 6), ('lagoftalmia', 6),
('asimetria facial', 6), ('desviacion de comisura oral', 6), ('desviacion de mandibula', 6),
('dificultad para masticar', 6), ('dificultad para beber', 6), ('dificultad para silbar', 6),
('disartria', 6), ('disfemia', 6), ('tartamudez', 6),
('disritmia del habla', 6), ('habla pegajosa', 6), ('habla explosiva', 6),
('habla nasal', 6), ('habla entrecortada', 6), ('habla arrastrada', 6),
('ataxia de marcha', 6), ('marcha espastica', 6), ('marcha parkinsoniana', 6),
('marcha festinante', 6), ('marcha propulsiva', 6), ('marcha retropulsiva', 6),
('marcha de talones', 6), ('marcha de puntillas', 6), ('marcha de base ancha', 6),
('marcha de base estrecha', 6), ('marcha vacilante', 6), ('marcha inestable', 6),
('temblor de reposo', 6), ('temblor de accion', 6), ('temblor intencional', 6),
('temblor de postura', 6), ('temblor grueso', 6), ('temblor fino', 6),
('movimientos involuntarios', 6), ('movimientos coreicos', 6), ('movimientos atetosicos', 6),
('movimientos balisticos', 6), ('movimientos mioclonicos', 6), ('movimientos distónicos', 6),
('espasmos musculares', 6), ('contracturas', 6), ('rigidez de desconexion', 6),
('rigidez de tuberia', 6), ('rigidez en rueda dentada', 6), ('hipertonia', 6),
('hipotonía', 6), ('reflejos aumentados', 6), ('reflejos disminuidos', 6),
('reflejos abolidos', 6), ('reflejo patologico', 6), ('signo de Babinski positivo', 6),
('clono', 6), ('clonus', 6), ('reflejo anal', 6);

-- GINECOLOGÍA - Aumentar a 60 sintomas
INSERT INTO sintomas_especialidad (palabra_clave, especialidad_id) VALUES
('ciclos menstruales irregulares', 7), ('ciclos muy frecuentes', 7), ('ciclos muy espaciados', 7),
('ciclos impredecibles', 7), ('sangrado intermenstrual', 7), ('sangrado postmenopausia', 7),
('manchas de sangre', 7), ('gotas de sangre', 7), ('perdida importante de sangre', 7),
('menstruacion prolongada', 7), ('menstruacion prolongadisima', 7), ('menstruacion muy abundante', 7),
('menstruacion casi nula', 7), ('ausencia de menstruacion', 7), ('retraso menstrual', 7),
('adelanto menstrual', 7), ('dolor previo a menstruacion', 7), ('dolor durante menstruacion', 7),
('dolor despues de menstruacion', 7), ('dolor pelvico cronico', 7), ('dolor pelvico agudo', 7),
('dolor pelvico intermitente', 7), ('dolor durante coito', 7), ('dolor despues de coito', 7),
('sangrado durante coito', 7), ('cambios en descarga vaginal', 7), ('descarga muy abundante', 7),
('descarga con olor desagradable', 7), ('descarga con color raro', 7), ('descarga gelatinosa', 7),
('descarga espumosa', 7), ('descarga tipo queso', 7), ('descarga con sangre', 7),
('picazon vulvar', 7), ('quemazón vulvar', 7), ('dolor vulvar', 7),
('ulceraciones en vulva', 7), ('ampollas en vulva', 7), ('lesiones en vulva', 7),
('cambios de piel vulvar', 7), ('enrojecimiento vulvar', 7), ('hinchazón vulvar', 7),
('cambios en piel vaginal', 7), ('resequedad vaginal', 7), ('fragilidad vaginal', 7),
('picazon vaginal', 7), ('quemazón vaginal', 7), ('dolor vaginal', 7),
('sangrado vaginal minimo', 7), ('sangrado vaginal leve', 7), ('sangrado vaginal moderado', 7),
('manchas oscuras en senos', 7), ('cambios en pezones', 7), ('inversion de pezon', 7),
('pezon plano', 7), ('pezon inflamado', 7), ('pezon con costras', 7),
('pezon con ulceracion', 7), ('pezon con sangre', 7), ('pezon con pus', 7),
('cambios en textura de mama', 7), ('mama con depresiones', 7), ('mama con protuberancias', 7),
('mama con hoyuelos', 7), ('mama tensa', 7), ('mama endurecida', 7);

-- ORTOPEDIA - Aumentar a 60 sintomas
INSERT INTO sintomas_especialidad (palabra_clave, especialidad_id) VALUES
('dolor en hombro', 8), ('dolor limitante en hombro', 8), ('imposibilidad de mover hombro', 8),
('dolor en codo', 8), ('dolor limitante en codo', 8), ('imposibilidad de mover codo', 8),
('dolor en muñeca', 8), ('dolor limitante en muñeca', 8), ('imposibilidad de mover muñeca', 8),
('dolor en mano', 8), ('dolor limitante en mano', 8), ('impossibilidad de usar mano', 8),
('dolor en cadera', 8), ('dolor limitante en cadera', 8), ('imposibilidad de mover cadera', 8),
('dolor en rodilla', 8), ('dolor limitante en rodilla', 8), ('imposibilidad de caminar', 8),
('dolor en tobillo', 8), ('dolor limitante en tobillo', 8), ('imposibilidad de pisar', 8),
('dolor en pie', 8), ('dolor limitante en pie', 8), ('imposibilidad de apoyar pie', 8),
('dolor en espalda baja', 8), ('dolor en espalda media', 8), ('dolor en espalda alta', 8),
('dolor en cuello', 8), ('dolor referido al brazo', 8), ('dolor referido a pierna', 8),
('dolor referido a mano', 8), ('dolor referido a pie', 8), ('dolor nocturno', 8),
('dolor matutino', 8), ('dolor vespertino', 8), ('dolor con el frio', 8),
('dolor con el calor', 8), ('dolor con humedad', 8), ('dolor con cambios climaticos', 8),
('dolor con el movimiento', 8), ('dolor con reposo', 8), ('dolor con presion', 8),
('dolor con masaje', 8), ('dolor con ejercicio', 8), ('dolor sin causa aparente', 8),
('dolor leve', 8), ('dolor moderado', 8), ('dolor severo', 8),
('dolor insoportable', 8), ('dolor punzante', 8), ('dolor quemante', 8),
('dolor pulsatil', 8), ('dolor adormecedor', 8), ('dolor entumecedor', 8),
('limitacion funcional leve', 8), ('limitacion funcional moderada', 8), ('limitacion funcional severa', 8),
('limitacion funcional total', 8), ('crujidos en articulaciones', 8), ('chasquidos en articulaciones', 8),
('bloqueos articulares', 8), ('inestabilidad articular', 8), ('cedencias de articulaciones', 8);

-- DERMATOLOGÍA - Aumentar a 60 sintomas
INSERT INTO sintomas_especialidad (palabra_clave, especialidad_id) VALUES
('erupcion localizada', 5), ('erupcion generalizada', 5), ('erupcion en cara', 5),
('erupcion en cuello', 5), ('erupcion en pecho', 5), ('erupcion en espalda', 5),
('erupcion en abdomen', 5), ('erupcion en brazos', 5), ('erupcion en manos', 5),
('erupcion en dedos', 5), ('erupcion en palmas', 5), ('erupcion en plantas', 5),
('erupcion en piernas', 5), ('erupcion en tobillos', 5), ('erupcion en pies', 5),
('erupcion en genitales', 5), ('erupcion en zona anal', 5), ('erupcion en pliegues', 5),
('erupcion dolorosa', 5), ('erupcion picante', 5), ('erupcion quemante', 5),
('erupcion pulsatil', 5), ('erupcion pruriginosa', 5), ('erupcion exudativa', 5),
('erupcion con pus', 5), ('erupcion con sangre', 5), ('erupcion con costras', 5),
('erupcion con escamas', 5), ('erupcion con descamacion', 5), ('erupcion con liquido', 5),
('erupcion con ampollas', 5), ('erupcion con vesiculas', 5), ('erupcion con pustulas', 5),
('erupcion con papulas', 5), ('erupcion con nodulos', 5), ('erupcion con tumefaccion', 5),
('erupcion roja', 5), ('erupcion violacea', 5), ('erupcion oscura', 5),
('erupcion clara', 5), ('erupcion amarillenta', 5), ('erupcion pardusca', 5),
('erupcion negruzca', 5), ('erupcion con bordes netos', 5), ('erupcion con bordes difusos', 5),
('erupcion simétrica', 5), ('erupcion asimetrica', 5), ('erupcion simetrica bilateral', 5),
('erupcion en distribucion dermatomal', 5), ('erupcion en distribucion linear', 5), ('erupcion en distribucion de ramas vasculares', 5),
('cambios de pigmentacion leve', 5), ('cambios de pigmentacion moderado', 5), ('cambios de pigmentacion severo', 5),
('hiperpigmentacion localizada', 5), ('hiperpigmentacion generalizada', 5), ('hipopigmentacion localizada', 5),
('hipopigmentacion generalizada', 5), ('vitiligo progresivo', 5), ('vitiligo estable', 5);

-- GASTROENTEROLOGÍA - Aumentar a 60 sintomas
INSERT INTO sintomas_especialidad (palabra_clave, especialidad_id) VALUES
('dolor epigastrico', 31), ('dolor periumbilical', 31), ('dolor en flanco derecho', 31),
('dolor en flanco izquierdo', 31), ('dolor infraxifoideo', 31), ('dolor suprapubico', 31),
('dolor en hipogastrio', 31), ('dolor generalizado abdominal', 31), ('dolor migratorio abdominal', 31),
('dolor cólico', 31), ('dolor tipo calambre', 31), ('dolor quemante', 31),
('dolor punzante', 31), ('dolor sordo', 31), ('dolor irradiado', 31),
('dolor con defecacion', 31), ('dolor con comida', 31), ('dolor con bebidas', 31),
('dolor con alcohol', 31), ('dolor con especias', 31), ('dolor con grasas', 31),
('dolor con frutas', 31), ('dolor con verduras', 31), ('dolor con productos lacteos', 31),
('dolor con gluten', 31), ('dolor que mejora con medicamento', 31), ('dolor que empeora con medicamento', 31),
('dolor nocturno', 31), ('dolor matutino', 31), ('dolor postprandial', 31),
('dolor con estrés', 31), ('dolor con reposo', 31), ('dolor con movimiento', 31),
('sensacion de plenitud prematura', 31), ('sensacion de saciedad rapida', 31), ('sensacion de distension', 31),
('sensacion de pesadez', 31), ('sensacion de hinchazón', 31), ('sensacion de gases', 31),
('sensacion de ruidos intestinales', 31), ('sensacion de borborigmos', 31), ('sensacion de movimientos', 31),
('cambios en ritmo defecatorio', 31), ('aumento de frecuencia de deposiciones', 31), ('disminucion de frecuencia de deposiciones', 31),
('deposiciones liquidas', 31), ('deposiciones blandas', 31), ('deposiciones normales', 31),
('deposiciones duras', 31), ('deposiciones en pelets', 31), ('deposiciones endurecidas', 31),
('cambios en color de deposiciones', 31), ('deposiciones pálidas', 31), ('deposiciones oscuras', 31),
('deposiciones rojas', 31), ('deposiciones negras', 31), ('deposiciones con moco', 31),
('deposiciones con sangre', 31), ('deposiciones con pus', 31), ('deposiciones con parasitos visibles', 31);

-- ENDOCRINOLOGÍA - Aumentar a 60 sintomas
INSERT INTO sintomas_especialidad (palabra_clave, especialidad_id) VALUES
('sed excesiva', 32), ('polidipsia', 32), ('boca muy seca', 32),
('orina excesiva', 32), ('poliuria', 32), ('nicturia', 32),
('enuresis nocturna', 32), ('hambre excesiva', 32), ('polifagia', 32),
('hambre constante', 32), ('deseo de comer dulces', 32), ('deseo de comer salado', 32),
('cambios en peso rapidos', 32), ('ganancia de peso inexplicable', 32), ('perdida de peso inexplicable', 32),
('redistribucion de grasa', 32), ('gordura concentrada en cara', 32), ('gordura concentrada en cuello', 32),
('gordura concentrada en espalda', 32), ('delgadez extrema', 32), ('desnutricion', 32),
('cambios en menstruacion', 32), ('menstruacion muy abundante', 32), ('menstruacion muy escasa', 32),
('ausencia de menstruacion en mujer fertil', 32), ('amenorrea secundaria', 32), ('ciclos irregulares', 32),
('impotencia sexual', 32), ('disminucion de libido', 32), ('aumento de libido', 32),
('cambios en capacidad reproductiva', 32), ('infertilidad', 32), ('esterilidad', 32),
('cambios en voz', 32), ('voz mas grave', 32), ('voz mas aguda', 32),
('cambios faciales', 32), ('cara redondeada', 32), ('cara afilada', 32),
('cambios en estructura ósea', 32), ('crecimiento excesivo', 32), ('gigantismo', 32),
('enanismo', 32), ('cambios en manos y pies', 32), ('manos y pies grandes', 32),
('manos y pies pequeños', 32), ('cambios en cabello', 32), ('cabello excesivo', 32),
('alopecia', 32), ('cabello en cara en mujer', 32), ('vello corporal excesivo', 32),
('falta de vello corporal', 32), ('cambios en piel', 32), ('piel mas oscura', 32),
('piel mas clara', 32), ('manchas en piel', 32), ('estrías en piel', 32),
('acne', 32), ('sebasis', 32), ('cambios en temperatura corporal', 32),
('intolerancia al frio', 32), ('intolerancia al calor', 32), ('cambios en sudoracion', 32);

-- NEUMOLOGÍA - Aumentar a 60 sintomas
INSERT INTO sintomas_especialidad (palabra_clave, especialidad_id) VALUES
('tos seca', 33), ('tos humeda', 33), ('tos con flema', 33),
('tos productive', 33), ('tos improductiva', 33), ('tos crónica', 33),
('tos aguda', 33), ('tos paroxistica', 33), ('tos nocturna', 33),
('tos matutina', 33), ('tos al esfuerzo', 33), ('tos con frio', 33),
('tos con calor', 33), ('tos con humedad', 33), ('tos con sequia', 33),
('tos con comidas', 33), ('tos con emociones', 33), ('tos con risa', 33),
('tos con llanto', 33), ('tos con hablando', 33), ('tos con acostarse', 33),
('tos con levantarse', 33), ('tos con ejercicio', 33), ('tos con reposo', 33),
('tos al respirar profundo', 33), ('tos que evita respirar profundo', 33), ('tos que causa dolor', 33),
('tos que causa vomito', 33), ('tos que causa sincope', 33), ('tos que causa incontinencia', 33),
('flema transparente', 33), ('flema blanca', 33), ('flema amarillenta', 33),
('flema verdosa', 33), ('flema herrumbrosa', 33), ('flema rosada', 33),
('flema sanguinolenta', 33), ('flema purulenta', 33), ('flema con olor', 33),
('flema abundante', 33), ('flema minima', 33), ('flema nula', 33),
('dificultad para expectorar', 33), ('expectoracion facil', 33), ('expectoracion dolorosa', 33),
('sibilancias', 33), ('ronquidos respiratorios', 33), ('estridor', 33),
('respiracion trabajosa', 33), ('respiracion superficial', 33), ('respiracion profunda', 33),
('respiracion rapida', 33), ('respiracion lenta', 33), ('respiracion irregular', 33),
('boca abierta al respirar', 33), ('aleteo nasal', 33), ('tiraje intercostal', 33),
('tiraje supraesternal', 33), ('tiraje subcostal', 33), ('cianosis central', 33),
('cianosis periferica', 33), ('dolor al respirar', 33), ('dolor pleuritico', 33);

-- UROLOGÍA - Aumentar a 60 sintomas
INSERT INTO sintomas_especialidad (palabra_clave, especialidad_id) VALUES
('disuria', 30), ('dolor al orinar', 30), ('ardor al orinar', 30),
('quemazón al orinar', 30), ('escozor al orinar', 30), ('dolor posterior a miccionar', 30),
('urgencia urinaria', 30), ('necesidad imperiosa de orinar', 30), ('imposibilidad de retener orina', 30),
('frecuencia urinaria aumentada', 30), ('poliuria diurna', 30), ('poliuria nocturna', 30),
('nicturia moderada', 30), ('nicturia severa', 30), ('enuresis nocturna', 30),
('vaciamiento incompleto', 30), ('sensacion de residuo', 30), ('goteo postmiccional', 30),
('incontinencia de urgencia', 30), ('incontinencia de esfuerzo', 30), ('incontinencia continua', 30),
('incontinencia con risa', 30), ('incontinencia con tos', 30), ('incontinencia con estornudo', 30),
('chorro urinario debil', 30), ('chorro urinario interrumpido', 30), ('chorro urinario bifido', 30),
('retardo en inicio de miccionar', 30), ('esfuerzo para orinar', 30), ('dificultad para iniciar miccionar', 30),
('color de orina oscuro', 30), ('color de orina claro', 30), ('color de orina rojo', 30),
('color de orina oscuro marron', 30), ('color de orina turbia', 30), ('olor de orina fuerte', 30),
('olor de orina desagradable', 30), ('olor de orina acetónico', 30), ('olor de orina frutal', 30),
('espuma en orina', 30), ('sedimento en orina', 30), ('cristales en orina', 30),
('cambios en volumen de orina', 30), ('volumen muy alto', 30), ('volumen muy bajo', 30),
('cambios en velocidad de orina', 30), ('chorro rápido', 30), ('chorro lento', 30),
('dolor en vejiga', 30), ('dolor en uretra', 30), ('dolor en prostata', 30),
('dolor perineal', 30), ('dolor escrotal', 30), ('dolor testicular', 30),
('dolor en pene', 30), ('dolor en punta de pene', 30), ('dolor en base de pene', 30),
('cambios en volumen testicular', 30), ('aumento de volumen testicular', 30), ('disminucion de volumen testicular', 30),
('dureza testicular', 30), ('ablandamiento testicular', 30), ('nódulos testiculares', 30);

SELECT COUNT(*) as total_sintomas FROM sintomas_especialidad;
